name: CI

on: [push]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
       node-version: '16'
     
   - name: Setting .env
     run: |
        echo "REACT_APP_PUBLIC_KEY = $REACT_APP_PUBLIC_KEY" >> .env
        echo "REACT_APP_KAKAO_KEY = $REACT_APP_KAKAO_KEY" >> .env
     env:
       REACT_APP_PUBLIC_KEY: ${{ secrets.REACT_APP_PUBLIC_KEY }}
       REACT_APP_KAKAO_KEY: ${{ secrets.REACT_KAKAO_KEY }}

      
  
  
